Compile v8.cc under C++11 mode using MinGW-w64 4.7.1
error: 'random' was not declared in this scope

WIN32 is not defined on C++11 mode, but _WIN32 is defined.
Simply change WIN32 to _WIN32 is enough

Change-Id: I8cad360945e7f31c34a70f54c754fafeffc2f36a
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>
Reviewed-by: Joerg Bornemann <joerg.bornemann@nokia.com>