[V8] Compile v8.cc under C++11 mode using MinGW-w64 4.7.1
error: 'random' was not declared in this scope

WIN32 is not defined on C++11 mode, but _WIN32 is defined.
Simply change WIN32 to _WIN32 is enough

Change-Id: I6a8ba5a3109b878161a21509d0e8b40f85451f23
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>
Reviewed-by: Joerg Bornemann <joerg.bornemann@nokia.com>
Reviewed-by: Yuchen Deng <loaden@gmail.com>
Reviewed-by: Lars Knoll <lars.knoll@digia.com>